-- +goose Up
ALTER TABLE users
    ALTER COLUMN id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at SET DEFAULT NOW(),
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DEFAULT NOW()
;

ALTER TABLE feeds
    ALTER COLUMN id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at SET DEFAULT NOW(),
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DEFAULT NOW()
;

-- +goose Down
ALTER TABLE users
    ALTER COLUMN id DROP DEFAULT ,
    ALTER COLUMN created_at TYPE TIMESTAMP,
    ALTER COLUMN created_at DROP DEFAULT ,
    ALTER COLUMN updated_at TYPE TIMESTAMP,
    ALTER COLUMN updated_at DROP DEFAULT 
;

ALTER TABLE feeds
    ALTER COLUMN id DROP DEFAULT ,
    ALTER COLUMN created_at TYPE TIMESTAMP,
    ALTER COLUMN created_at DROP DEFAULT ,
    ALTER COLUMN updated_at TYPE TIMESTAMP,
    ALTER COLUMN updated_at DROP DEFAULT 
;